version: '3'

services:

# backend container #
  backend:
    build: ./backend
    expose:
      - "9000"
    environment:
      API_HOST: localhost
      APP_SERVER_PORT: "9000"
    ports:
      - 9000:9000
    volumes:
      - ./backend/src:/srv/app/backend/src
    command: npm start

# frontend container #
  frontend:
    build: ./frontend
    environment:
      - REACT_APP_PORT=8000
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./frontend/src:/srv/app/frontend/src
      - ./frontend/src/public:/srv/app/frontend/src/public
    links:
      - backend
    command: npm start